export const fontFamily = {
  ttFors: [
    'TT Fors',
    'ui-sans-serif',
    'system-ui',
    '-apple-system',
    'BlinkMacSystemFont',
    'Segoe UI',
    'Roboto',
    'Helvetica Neue',
    'Arial',
    'Noto Sans',
    'sans-serif',
  ],
  ttInterphrasesMono: [
    'TT Interphases Mono',
    'ui-sans-serif',
    'system-ui',
    '-apple-system',
    'BlinkMacSystemFont',
    'Segoe UI',
    'Roboto',
    'Helvetica Neue',
    'Arial',
    'Noto Sans',
    'sans-serif',
  ],
};

export const fontSize = {
  xs: ['12px', '18px'],
  sm: ['14px', '21px'],
  base: ['16px', '24px'],
  lg: ['18px', '27px'],
  xl: ['20px', '30px'],
  '2xl': ['24px', '36px'],
  '3xl': ['30px', '45px'],
  '4xl': ['36px', '54px'],
  '5xl': ['48px', '62.4px'],
  '6xl': ['60px', '90px'],
  '7xl': ['72px', '108px'],
  '8xl': ['96px', '144px'],
  '9xl': ['128px', '192px'],
};
